package com.b3a5t001.blocklust.datagen;

import com.b3a5t001.blocklust.blocks.ModBlocks;
import com.b3a5t001.blocklust.blocks.ModMossBlocks;
import com.b3a5t001.blocklust.blocks.ModPlanks;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.minecraft.block.Block;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.enchantment.Enchantments;
import net.minecraft.item.Item;
import net.minecraft.item.Items;
import net.minecraft.loot.LootTable;
import net.minecraft.loot.entry.ItemEntry;
import net.minecraft.loot.entry.LeafEntry;
import net.minecraft.loot.function.ApplyBonusLootFunction;
import net.minecraft.loot.function.SetCountLootFunction;
import net.minecraft.loot.provider.number.UniformLootNumberProvider;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class ModLootTableProvider extends FabricBlockLootTableProvider {

    public ModLootTableProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {
        addDrop(ModBlocks.ANDESITE_BRICKS);
        addDrop(ModBlocks.ANDESITE_BRICK_SLAB, slabDrops(ModBlocks.ANDESITE_BRICK_SLAB));
        addDrop(ModBlocks.ANDESITE_BRICK_STAIRS);
        addDrop(ModBlocks.ANDESITE_BRICK_WALL);
        addDrop(ModMossBlocks.MOSSY_ANDESITE_BRICKS);
        addDrop(ModMossBlocks.MOSSY_ANDESITE_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_ANDESITE_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_ANDESITE_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_ANDESITE_BRICK_WALL);
        addDrop(ModBlocks.CRACKED_ANDESITE_BRICKS);
        addDrop(ModBlocks.ANDESITE_TILES);
        addDrop(ModBlocks.ANDESITE_TILE_SLAB, slabDrops(ModBlocks.ANDESITE_TILE_SLAB));
        addDrop(ModBlocks.ANDESITE_TILE_STAIRS);
        addDrop(ModBlocks.ANDESITE_TILE_WALL);
        addDrop(ModMossBlocks.MOSSY_ANDESITE_TILES);
        addDrop(ModMossBlocks.MOSSY_ANDESITE_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_ANDESITE_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_ANDESITE_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_ANDESITE_TILE_WALL);
        addDrop(ModBlocks.CRACKED_ANDESITE_TILES);
        addDrop(ModBlocks.POLISHED_ANDESITE_WALL);
        addDrop(ModBlocks.GRANITE_BRICKS);
        addDrop(ModBlocks.GRANITE_BRICK_SLAB, slabDrops(ModBlocks.GRANITE_BRICK_SLAB));
        addDrop(ModBlocks.GRANITE_BRICK_STAIRS);
        addDrop(ModBlocks.GRANITE_BRICK_WALL);
        addDrop(ModMossBlocks.MOSSY_GRANITE_BRICKS);
        addDrop(ModMossBlocks.MOSSY_GRANITE_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_GRANITE_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_GRANITE_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_GRANITE_BRICK_WALL);
        addDrop(ModBlocks.CRACKED_GRANITE_BRICKS);
        addDrop(ModBlocks.GRANITE_TILES);
        addDrop(ModBlocks.GRANITE_TILE_SLAB, slabDrops(ModBlocks.GRANITE_TILE_SLAB));
        addDrop(ModBlocks.GRANITE_TILE_STAIRS);
        addDrop(ModBlocks.GRANITE_TILE_WALL);
        addDrop(ModMossBlocks.MOSSY_GRANITE_TILES);
        addDrop(ModMossBlocks.MOSSY_GRANITE_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_GRANITE_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_GRANITE_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_GRANITE_TILE_WALL);
        addDrop(ModBlocks.CRACKED_GRANITE_TILES);
        addDrop(ModBlocks.POLISHED_GRANITE_WALL);
        addDrop(ModBlocks.DIORITE_BRICKS);
        addDrop(ModBlocks.DIORITE_BRICK_SLAB, slabDrops(ModBlocks.DIORITE_BRICK_SLAB));
        addDrop(ModBlocks.DIORITE_BRICK_STAIRS);
        addDrop(ModBlocks.DIORITE_BRICK_WALL);
        addDrop(ModMossBlocks.MOSSY_DIORITE_BRICKS);
        addDrop(ModMossBlocks.MOSSY_DIORITE_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_DIORITE_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_DIORITE_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_DIORITE_BRICK_WALL);
        addDrop(ModBlocks.CRACKED_DIORITE_BRICKS);
        addDrop(ModBlocks.DIORITE_TILES);
        addDrop(ModBlocks.DIORITE_TILE_SLAB, slabDrops(ModBlocks.DIORITE_TILE_SLAB));
        addDrop(ModBlocks.DIORITE_TILE_STAIRS);
        addDrop(ModBlocks.DIORITE_TILE_WALL);
        addDrop(ModMossBlocks.MOSSY_DIORITE_TILES);
        addDrop(ModMossBlocks.MOSSY_DIORITE_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_DIORITE_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_DIORITE_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_DIORITE_TILE_WALL);
        addDrop(ModBlocks.CRACKED_DIORITE_TILES);
        addDrop(ModBlocks.POLISHED_DIORITE_WALL);
        addDrop(ModBlocks.STONE_TILES);
        addDrop(ModBlocks.STONE_TILE_SLAB, slabDrops(ModBlocks.STONE_TILE_SLAB));
        addDrop(ModBlocks.STONE_TILE_STAIRS);
        addDrop(ModBlocks.STONE_TILE_WALL);
        addDrop(ModMossBlocks.MOSSY_STONE_TILES);
        addDrop(ModMossBlocks.MOSSY_STONE_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_STONE_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_STONE_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_STONE_TILE_WALL);
        addDrop(ModBlocks.CRACKED_STONE_TILES);
        addDrop(ModBlocks.SMOOTH_STONE_STAIRS);
        addDrop(ModBlocks.SMOOTH_STONE_WALL);
        addDrop(ModBlocks.STONE_WALL);
        addDrop(ModPlanks.CACTUS_FRAME);
        addDrop(ModPlanks.CACTUS_PLANKS);
        addDrop(ModPlanks.CACTUS_SLAB, slabDrops(ModPlanks.CACTUS_SLAB));
        addDrop(ModPlanks.CACTUS_STAIRS);
        addDrop(ModPlanks.CACTUS_FENCE);
        addDrop(ModPlanks.CACTUS_FENCE_GATE);
        addDrop(ModPlanks.CACTUS_DOOR, doorDrops(ModPlanks.CACTUS_DOOR));
        addDrop(ModPlanks.CACTUS_TRAPDOOR);
        addDrop(ModPlanks.CACTUS_BUTTON);
        addDrop(ModPlanks.CACTUS_PRESSURE_PLATE);
        addDrop(ModPlanks.MOSSY_CACTUS_PLANKS);
        addDrop(ModPlanks.MOSSY_CACTUS_SLAB, slabDrops(ModPlanks.MOSSY_CACTUS_SLAB));
        addDrop(ModPlanks.MOSSY_CACTUS_STAIRS);
        addDrop(ModPlanks.MOSSY_CACTUS_FENCE);
        addDrop(ModPlanks.MOSSY_CACTUS_FENCE_GATE);
        addDrop(ModPlanks.MOSSY_WARPED_PLANKS);
        addDrop(ModPlanks.MOSSY_WARPED_SLAB, slabDrops(ModPlanks.MOSSY_WARPED_SLAB));
        addDrop(ModPlanks.MOSSY_WARPED_STAIRS);
        addDrop(ModPlanks.MOSSY_WARPED_FENCE);
        addDrop(ModPlanks.MOSSY_WARPED_FENCE_GATE);
        addDrop(ModPlanks.MOSSY_SPRUCE_PLANKS);
        addDrop(ModPlanks.MOSSY_SPRUCE_SLAB, slabDrops(ModPlanks.MOSSY_SPRUCE_SLAB));
        addDrop(ModPlanks.MOSSY_SPRUCE_STAIRS);
        addDrop(ModPlanks.MOSSY_SPRUCE_FENCE);
        addDrop(ModPlanks.MOSSY_SPRUCE_FENCE_GATE);
        addDrop(ModPlanks.MOSSY_OAK_PLANKS);
        addDrop(ModPlanks.MOSSY_OAK_SLAB, slabDrops(ModPlanks.MOSSY_OAK_SLAB));
        addDrop(ModPlanks.MOSSY_OAK_STAIRS);
        addDrop(ModPlanks.MOSSY_OAK_FENCE);
        addDrop(ModPlanks.MOSSY_OAK_FENCE_GATE);
        addDrop(ModPlanks.MOSSY_MANGROVE_PLANKS);
        addDrop(ModPlanks.MOSSY_MANGROVE_SLAB, slabDrops(ModPlanks.MOSSY_MANGROVE_SLAB));
        addDrop(ModPlanks.MOSSY_MANGROVE_STAIRS);
        addDrop(ModPlanks.MOSSY_MANGROVE_FENCE);
        addDrop(ModPlanks.MOSSY_MANGROVE_FENCE_GATE);
        addDrop(ModPlanks.MOSSY_JUNGLE_PLANKS);
        addDrop(ModPlanks.MOSSY_JUNGLE_SLAB, slabDrops(ModPlanks.MOSSY_JUNGLE_SLAB));
        addDrop(ModPlanks.MOSSY_JUNGLE_STAIRS);
        addDrop(ModPlanks.MOSSY_JUNGLE_FENCE);
        addDrop(ModPlanks.MOSSY_JUNGLE_FENCE_GATE);
        addDrop(ModPlanks.MOSSY_DARK_OAK_PLANKS);
        addDrop(ModPlanks.MOSSY_DARK_OAK_SLAB, slabDrops(ModPlanks.MOSSY_DARK_OAK_SLAB));
        addDrop(ModPlanks.MOSSY_DARK_OAK_STAIRS);
        addDrop(ModPlanks.MOSSY_DARK_OAK_FENCE);
        addDrop(ModPlanks.MOSSY_DARK_OAK_FENCE_GATE);
        addDrop(ModPlanks.MOSSY_CRIMSON_PLANKS);
        addDrop(ModPlanks.MOSSY_CRIMSON_SLAB, slabDrops(ModPlanks.MOSSY_CRIMSON_SLAB));
        addDrop(ModPlanks.MOSSY_CRIMSON_STAIRS);
        addDrop(ModPlanks.MOSSY_CRIMSON_FENCE);
        addDrop(ModPlanks.MOSSY_CRIMSON_FENCE_GATE);
        addDrop(ModPlanks.MOSSY_CHERRY_PLANKS);
        addDrop(ModPlanks.MOSSY_CHERRY_SLAB, slabDrops(ModPlanks.MOSSY_CHERRY_SLAB));
        addDrop(ModPlanks.MOSSY_CHERRY_STAIRS);
        addDrop(ModPlanks.MOSSY_CHERRY_FENCE);
        addDrop(ModPlanks.MOSSY_CHERRY_FENCE_GATE);
        addDrop(ModPlanks.MOSSY_BIRCH_PLANKS);
        addDrop(ModPlanks.MOSSY_BIRCH_SLAB, slabDrops(ModPlanks.MOSSY_BIRCH_SLAB));
        addDrop(ModPlanks.MOSSY_BIRCH_STAIRS);
        addDrop(ModPlanks.MOSSY_BIRCH_FENCE);
        addDrop(ModPlanks.MOSSY_BIRCH_FENCE_GATE);
        addDrop(ModPlanks.MOSSY_BAMBOO_MOSAIC);
        addDrop(ModPlanks.MOSSY_BAMBOO_MOSAIC_SLAB, slabDrops(ModPlanks.MOSSY_BAMBOO_MOSAIC_SLAB));
        addDrop(ModPlanks.MOSSY_BAMBOO_MOSAIC_STAIRS);
        addDrop(ModPlanks.MOSSY_BAMBOO_PLANKS);
        addDrop(ModPlanks.MOSSY_BAMBOO_SLAB, slabDrops(ModPlanks.MOSSY_BAMBOO_SLAB));
        addDrop(ModPlanks.MOSSY_BAMBOO_STAIRS);
        addDrop(ModPlanks.MOSSY_BAMBOO_FENCE);
        addDrop(ModPlanks.MOSSY_BAMBOO_FENCE_GATE);
        addDrop(ModPlanks.MOSSY_ACACIA_PLANKS);
        addDrop(ModPlanks.MOSSY_ACACIA_SLAB, slabDrops(ModPlanks.MOSSY_ACACIA_SLAB));
        addDrop(ModPlanks.MOSSY_ACACIA_STAIRS);
        addDrop(ModPlanks.MOSSY_ACACIA_FENCE);
        addDrop(ModPlanks.MOSSY_ACACIA_FENCE_GATE);
        addDrop(ModMossBlocks.MOSSY_MUD_BRICKS);
        addDrop(ModMossBlocks.MOSSY_MUD_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_MUD_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_MUD_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_MUD_BRICK_WALL);
        addDrop(ModMossBlocks.MOSSY_BRICKS);
        addDrop(ModMossBlocks.MOSSY_BASALT_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_BASALT_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_BRICK_WALL);
        addDrop(ModMossBlocks.MOSSY_NETHER_BRICKS);
        addDrop(ModMossBlocks.MOSSY_NETHER_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_NETHER_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_NETHER_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_NETHER_BRICK_WALL);
        addDrop(ModMossBlocks.MOSSY_RED_NETHER_BRICKS);
        addDrop(ModMossBlocks.MOSSY_RED_NETHER_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_RED_NETHER_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_RED_NETHER_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_RED_NETHER_BRICK_WALL);
        addDrop(ModBlocks.CRACKED_RED_NETHER_BRICKS);
        addDrop(ModBlocks.CALCITE_SLAB, slabDrops(ModBlocks.CALCITE_SLAB));
        addDrop(ModBlocks.CALCITE_STAIRS);
        addDrop(ModBlocks.CALCITE_WALL);
        addDrop(ModBlocks.POLISHED_CALCITE);
        addDrop(ModBlocks.POLISHED_CALCITE_SLAB, slabDrops(ModBlocks.POLISHED_CALCITE_SLAB));
        addDrop(ModBlocks.POLISHED_CALCITE_STAIRS);
        addDrop(ModBlocks.POLISHED_CALCITE_WALL);
        addDrop(ModBlocks.CALCITE_BRICKS);
        addDrop(ModBlocks.CALCITE_BRICK_SLAB, slabDrops(ModBlocks.CALCITE_BRICK_SLAB));
        addDrop(ModBlocks.CALCITE_BRICK_STAIRS);
        addDrop(ModBlocks.CALCITE_BRICK_WALL);
        addDrop(ModMossBlocks.MOSSY_CALCITE_BRICKS);
        addDrop(ModMossBlocks.MOSSY_CALCITE_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_CALCITE_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_CALCITE_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_CALCITE_BRICK_WALL);
        addDrop(ModBlocks.CRACKED_CALCITE_BRICKS);
        addDrop(ModBlocks.CALCITE_TILES);
        addDrop(ModBlocks.CALCITE_TILE_SLAB, slabDrops(ModBlocks.CALCITE_TILE_SLAB));
        addDrop(ModBlocks.CALCITE_TILE_STAIRS);
        addDrop(ModBlocks.CALCITE_TILE_WALL);
        addDrop(ModMossBlocks.MOSSY_CALCITE_TILES);
        addDrop(ModMossBlocks.MOSSY_CALCITE_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_CALCITE_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_CALCITE_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_CALCITE_TILE_WALL);
        addDrop(ModBlocks.CRACKED_CALCITE_TILES);
        addDrop(ModBlocks.NETHERRACK_SLAB, slabDrops(ModBlocks.NETHERRACK_SLAB));
        addDrop(ModBlocks.NETHERRACK_STAIRS);
        addDrop(ModBlocks.NETHERRACK_WALL);
        addDrop(ModBlocks.POLISHED_NETHERRACK);
        addDrop(ModBlocks.POLISHED_NETHERRACK_SLAB, slabDrops(ModBlocks.POLISHED_NETHERRACK_SLAB));
        addDrop(ModBlocks.POLISHED_NETHERRACK_STAIRS);
        addDrop(ModBlocks.POLISHED_NETHERRACK_WALL);
        addDrop(ModBlocks.NETHERRACK_BRICKS);
        addDrop(ModBlocks.NETHERRACK_BRICK_SLAB, slabDrops(ModBlocks.NETHERRACK_BRICK_SLAB));
        addDrop(ModBlocks.NETHERRACK_BRICK_STAIRS);
        addDrop(ModBlocks.NETHERRACK_BRICK_WALL);
        addDrop(ModMossBlocks.MOSSY_NETHERRACK_BRICKS);
        addDrop(ModMossBlocks.MOSSY_NETHERRACK_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_NETHERRACK_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_NETHERRACK_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_NETHERRACK_BRICK_WALL);
        addDrop(ModBlocks.CRACKED_NETHERRACK_BRICKS);
        addDrop(ModBlocks.NETHERRACK_TILES);
        addDrop(ModBlocks.NETHERRACK_TILE_SLAB, slabDrops(ModBlocks.NETHERRACK_TILE_SLAB));
        addDrop(ModBlocks.NETHERRACK_TILE_STAIRS);
        addDrop(ModBlocks.NETHERRACK_TILE_WALL);
        addDrop(ModMossBlocks.MOSSY_NETHERRACK_TILES);
        addDrop(ModMossBlocks.MOSSY_NETHERRACK_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_NETHERRACK_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_NETHERRACK_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_NETHERRACK_TILE_WALL);
        addDrop(ModBlocks.CRACKED_NETHERRACK_TILES);
        addDrop(ModBlocks.END_STONE_SLAB, slabDrops(ModBlocks.END_STONE_SLAB));
        addDrop(ModBlocks.END_STONE_STAIRS);
        addDrop(ModBlocks.END_STONE_WALL);
        addDrop(ModMossBlocks.MOSSY_END_STONE_BRICKS);
        addDrop(ModMossBlocks.MOSSY_END_STONE_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_END_STONE_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_END_STONE_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_END_STONE_BRICK_WALL);
        addDrop(ModBlocks.CRACKED_END_STONE_BRICKS);
        addDrop(ModBlocks.END_STONE_TILES);
        addDrop(ModBlocks.END_STONE_TILE_SLAB, slabDrops(ModBlocks.END_STONE_TILE_SLAB));
        addDrop(ModBlocks.END_STONE_TILE_STAIRS);
        addDrop(ModBlocks.END_STONE_TILE_WALL);
        addDrop(ModMossBlocks.MOSSY_END_STONE_TILES);
        addDrop(ModMossBlocks.MOSSY_END_STONE_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_END_STONE_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_END_STONE_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_END_STONE_TILE_WALL);
        addDrop(ModBlocks.CRACKED_END_STONE_TILES);
        addDrop(ModBlocks.QUARTZ_WALL);
        addDrop(ModBlocks.SMOOTH_QUARTZ_WALL);
        addDrop(ModBlocks.QUARTZ_BRICK_SLAB, slabDrops(ModBlocks.QUARTZ_BRICK_SLAB));
        addDrop(ModBlocks.QUARTZ_BRICK_STAIRS);
        addDrop(ModBlocks.QUARTZ_BRICK_WALL);
        addDrop(ModMossBlocks.MOSSY_QUARTZ_BRICKS);
        addDrop(ModMossBlocks.MOSSY_QUARTZ_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_QUARTZ_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_QUARTZ_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_QUARTZ_BRICK_WALL);
        addDrop(ModBlocks.CRACKED_QUARTZ_BRICKS);
        addDrop(ModBlocks.QUARTZ_TILES);
        addDrop(ModBlocks.QUARTZ_TILE_SLAB, slabDrops(ModBlocks.QUARTZ_TILE_SLAB));
        addDrop(ModBlocks.QUARTZ_TILE_STAIRS);
        addDrop(ModBlocks.QUARTZ_TILE_WALL);
        addDrop(ModMossBlocks.MOSSY_QUARTZ_TILES);
        addDrop(ModMossBlocks.MOSSY_QUARTZ_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_QUARTZ_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_QUARTZ_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_QUARTZ_TILE_WALL);
        addDrop(ModBlocks.PURPUR_WALL);
        addDrop(ModBlocks.PURPUR_BRICKS);
        addDrop(ModBlocks.PURPUR_BRICK_SLAB, slabDrops(ModBlocks.PURPUR_BRICK_SLAB));
        addDrop(ModBlocks.PURPUR_BRICK_STAIRS);
        addDrop(ModBlocks.PURPUR_BRICK_WALL);
        addDrop(ModMossBlocks.MOSSY_PURPUR_BRICKS);
        addDrop(ModMossBlocks.MOSSY_PURPUR_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_PURPUR_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_PURPUR_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_PURPUR_BRICK_WALL);
        addDrop(ModBlocks.CRACKED_PURPUR_BRICKS);
        addDrop(ModBlocks.PURPUR_TILES);
        addDrop(ModBlocks.PURPUR_TILE_SLAB, slabDrops(ModBlocks.PURPUR_TILE_SLAB));
        addDrop(ModBlocks.PURPUR_TILE_STAIRS);
        addDrop(ModBlocks.PURPUR_TILE_WALL);
        addDrop(ModMossBlocks.MOSSY_PURPUR_TILES);
        addDrop(ModMossBlocks.MOSSY_PURPUR_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_PURPUR_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_PURPUR_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_PURPUR_TILE_WALL);
        addDrop(ModBlocks.CRACKED_PURPUR_TILES);
        addDrop(ModBlocks.DARK_PRISMARINE_WALL);
        addDrop(ModBlocks.DARK_PRISMARINE_BRICKS);
        addDrop(ModBlocks.DARK_PRISMARINE_BRICK_SLAB, slabDrops(ModBlocks.DARK_PRISMARINE_BRICK_SLAB));
        addDrop(ModBlocks.DARK_PRISMARINE_BRICK_STAIRS);
        addDrop(ModBlocks.DARK_PRISMARINE_BRICK_WALL);
        addDrop(ModMossBlocks.MOSSY_DARK_PRISMARINE_BRICKS);
        addDrop(ModMossBlocks.MOSSY_DARK_PRISMARINE_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_DARK_PRISMARINE_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_DARK_PRISMARINE_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_DARK_PRISMARINE_BRICK_WALL);
        addDrop(ModBlocks.CRACKED_DARK_PRISMARINE_BRICKS);
        addDrop(ModBlocks.DARK_PRISMARINE_TILES);
        addDrop(ModBlocks.DARK_PRISMARINE_TILE_SLAB, slabDrops(ModBlocks.DARK_PRISMARINE_TILE_SLAB));
        addDrop(ModBlocks.DARK_PRISMARINE_TILE_STAIRS);
        addDrop(ModBlocks.DARK_PRISMARINE_TILE_WALL);
        addDrop(ModMossBlocks.MOSSY_DARK_PRISMARINE_TILES);
        addDrop(ModMossBlocks.MOSSY_DARK_PRISMARINE_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_DARK_PRISMARINE_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_DARK_PRISMARINE_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_DARK_PRISMARINE_TILE_WALL);
        addDrop(ModBlocks.CRACKED_DARK_PRISMARINE_TILES);
        addDrop(ModBlocks.DRIPSTONE_SLAB, slabDrops(ModBlocks.DRIPSTONE_SLAB));
        addDrop(ModBlocks.DRIPSTONE_STAIRS);
        addDrop(ModBlocks.DRIPSTONE_WALL);
        addDrop(ModBlocks.POLISHED_DRIPSTONE);
        addDrop(ModBlocks.POLISHED_DRIPSTONE_SLAB, slabDrops(ModBlocks.POLISHED_DRIPSTONE_SLAB));
        addDrop(ModBlocks.POLISHED_DRIPSTONE_STAIRS);
        addDrop(ModBlocks.POLISHED_DRIPSTONE_WALL);
        addDrop(ModBlocks.DRIPSTONE_BRICKS);
        addDrop(ModBlocks.DRIPSTONE_BRICK_SLAB, slabDrops(ModBlocks.DRIPSTONE_BRICK_SLAB));
        addDrop(ModBlocks.DRIPSTONE_BRICK_STAIRS);
        addDrop(ModBlocks.DRIPSTONE_BRICK_WALL);
        addDrop(ModMossBlocks.MOSSY_DRIPSTONE_BRICKS);
        addDrop(ModMossBlocks.MOSSY_DRIPSTONE_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_DRIPSTONE_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_DRIPSTONE_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_DRIPSTONE_BRICK_WALL);
        addDrop(ModBlocks.CRACKED_DRIPSTONE_BRICKS);
        addDrop(ModBlocks.DRIPSTONE_TILES);
        addDrop(ModBlocks.DRIPSTONE_TILE_SLAB, slabDrops(ModBlocks.DRIPSTONE_TILE_SLAB));
        addDrop(ModBlocks.DRIPSTONE_TILE_STAIRS);
        addDrop(ModBlocks.DRIPSTONE_TILE_WALL);
        addDrop(ModMossBlocks.MOSSY_DRIPSTONE_TILES);
        addDrop(ModMossBlocks.MOSSY_DRIPSTONE_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_DRIPSTONE_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_DRIPSTONE_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_DRIPSTONE_TILE_WALL);
        addDrop(ModBlocks.CRACKED_DRIPSTONE_TILES);
        addDrop(ModMossBlocks.MOSSY_TUFF_BRICKS);
        addDrop(ModMossBlocks.MOSSY_TUFF_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_TUFF_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_TUFF_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_TUFF_BRICK_WALL);
        addDrop(ModBlocks.CRACKED_TUFF_BRICKS);
        addDrop(ModBlocks.TUFF_TILES);
        addDrop(ModBlocks.TUFF_TILE_SLAB, slabDrops(ModBlocks.TUFF_TILE_SLAB));
        addDrop(ModBlocks.TUFF_TILE_STAIRS);
        addDrop(ModBlocks.TUFF_TILE_WALL);
        addDrop(ModMossBlocks.MOSSY_TUFF_TILES);
        addDrop(ModMossBlocks.MOSSY_TUFF_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_TUFF_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_TUFF_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_TUFF_TILE_WALL);
        addDrop(ModBlocks.CRACKED_TUFF_TILES);
        addDrop(ModBlocks.PRISMARINE_BRICK_WALL);
        addDrop(ModMossBlocks.MOSSY_PRISMARINE_BRICKS);
        addDrop(ModMossBlocks.MOSSY_PRISMARINE_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_PRISMARINE_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_PRISMARINE_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_PRISMARINE_BRICK_WALL);
        addDrop(ModBlocks.CRACKED_PRISMARINE_BRICKS);
        addDrop(ModBlocks.PRISMARINE_TILES);
        addDrop(ModBlocks.PRISMARINE_TILE_SLAB, slabDrops(ModBlocks.PRISMARINE_TILE_SLAB));
        addDrop(ModBlocks.PRISMARINE_TILE_STAIRS);
        addDrop(ModBlocks.PRISMARINE_TILE_WALL);
        addDrop(ModMossBlocks.MOSSY_PRISMARINE_TILES);
        addDrop(ModMossBlocks.MOSSY_PRISMARINE_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_PRISMARINE_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_PRISMARINE_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_PRISMARINE_TILE_WALL);
        addDrop(ModBlocks.CRACKED_PRISMARINE_TILES);
        addDrop(ModMossBlocks.MOSSY_POLISHED_BLACKSTONE_BRICKS);
        addDrop(ModMossBlocks.MOSSY_POLISHED_BLACKSTONE_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_POLISHED_BLACKSTONE_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_POLISHED_BLACKSTONE_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_POLISHED_BLACKSTONE_BRICK_WALL);
        addDrop(ModBlocks.POLISHED_BLACKSTONE_TILES);
        addDrop(ModBlocks.POLISHED_BLACKSTONE_TILE_SLAB, slabDrops(ModBlocks.POLISHED_BLACKSTONE_TILE_SLAB));
        addDrop(ModBlocks.POLISHED_BLACKSTONE_TILE_STAIRS);
        addDrop(ModBlocks.POLISHED_BLACKSTONE_TILE_WALL);
        addDrop(ModMossBlocks.MOSSY_POLISHED_BLACKSTONE_TILES);
        addDrop(ModMossBlocks.MOSSY_POLISHED_BLACKSTONE_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_POLISHED_BLACKSTONE_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_POLISHED_BLACKSTONE_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_POLISHED_BLACKSTONE_TILE_WALL);
        addDrop(ModBlocks.CRACKED_POLISHED_BLACKSTONE_TILES);
        addDrop(ModBlocks.CUT_POLISHED_BASALT);
        addDrop(ModBlocks.CUT_POLISHED_BASALT_SLAB, slabDrops(ModBlocks.CUT_POLISHED_BASALT_SLAB));
        addDrop(ModBlocks.CUT_POLISHED_BASALT_STAIRS);
        addDrop(ModBlocks.CUT_POLISHED_BASALT_WALL);
        addDrop(ModBlocks.BASALT_BRICKS);
        addDrop(ModBlocks.BASALT_BRICK_SLAB, slabDrops(ModBlocks.BASALT_BRICK_SLAB));
        addDrop(ModBlocks.BASALT_BRICK_STAIRS);
        addDrop(ModBlocks.BASALT_BRICK_WALL);
        addDrop(ModMossBlocks.MOSSY_BASALT_BRICKS);
        addDrop(ModMossBlocks.MOSSY_BASALT_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_BASALT_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_BASALT_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_BASALT_BRICK_WALL);
        addDrop(ModBlocks.CRACKED_BASALT_BRICKS);
        addDrop(ModBlocks.BASALT_TILES);
        addDrop(ModBlocks.BASALT_TILE_SLAB, slabDrops(ModBlocks.BASALT_TILE_SLAB));
        addDrop(ModBlocks.BASALT_TILE_STAIRS);
        addDrop(ModBlocks.BASALT_TILE_WALL);
        addDrop(ModMossBlocks.MOSSY_BASALT_TILES);
        addDrop(ModMossBlocks.MOSSY_BASALT_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_BASALT_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_BASALT_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_BASALT_TILE_WALL);
        addDrop(ModBlocks.CRACKED_BASALT_TILES);
        addDrop(ModMossBlocks.MOSSY_DEEPSLATE_BRICKS);
        addDrop(ModMossBlocks.MOSSY_DEEPSLATE_BRICK_SLAB, slabDrops(ModMossBlocks.MOSSY_DEEPSLATE_BRICK_SLAB));
        addDrop(ModMossBlocks.MOSSY_DEEPSLATE_BRICK_STAIRS);
        addDrop(ModMossBlocks.MOSSY_DEEPSLATE_BRICK_WALL);
        addDrop(ModMossBlocks.MOSSY_DEEPSLATE_TILES);
        addDrop(ModMossBlocks.MOSSY_DEEPSLATE_TILE_SLAB, slabDrops(ModMossBlocks.MOSSY_DEEPSLATE_TILE_SLAB));
        addDrop(ModMossBlocks.MOSSY_DEEPSLATE_TILE_STAIRS);
        addDrop(ModMossBlocks.MOSSY_DEEPSLATE_TILE_WALL);
        addDrop(ModBlocks.ANDESITE_COAL_ORE, oreDrops(ModBlocks.ANDESITE_COAL_ORE, Items.COAL));
        addDrop(ModBlocks.ANDESITE_EMERALD_ORE, oreDrops(ModBlocks.ANDESITE_EMERALD_ORE, Items.EMERALD));
        addDrop(ModBlocks.ANDESITE_IRON_ORE, oreDrops(ModBlocks.ANDESITE_IRON_ORE, Items.RAW_IRON));
        addDrop(ModBlocks.ANDESITE_GOLD_ORE, oreDrops(ModBlocks.ANDESITE_GOLD_ORE, Items.RAW_GOLD));
        addDrop(ModBlocks.ANDESITE_DIAMOND_ORE, oreDrops(ModBlocks.ANDESITE_DIAMOND_ORE, Items.DIAMOND));
        addDrop(ModBlocks.ANDESITE_COPPER_ORE, copperOreDrops(ModBlocks.ANDESITE_COPPER_ORE));
        addDrop(ModBlocks.ANDESITE_LAPIS_ORE, lapisOreDrops(ModBlocks.ANDESITE_LAPIS_ORE));
        addDrop(ModBlocks.ANDESITE_REDSTONE_ORE, redstoneOreDrops(ModBlocks.ANDESITE_REDSTONE_ORE));
        addDrop(ModBlocks.GRANITE_COAL_ORE, oreDrops(ModBlocks.GRANITE_COAL_ORE, Items.COAL));
        addDrop(ModBlocks.GRANITE_EMERALD_ORE, oreDrops(ModBlocks.GRANITE_EMERALD_ORE, Items.EMERALD));
        addDrop(ModBlocks.GRANITE_IRON_ORE, oreDrops(ModBlocks.GRANITE_IRON_ORE, Items.RAW_IRON));
        addDrop(ModBlocks.GRANITE_GOLD_ORE, oreDrops(ModBlocks.GRANITE_GOLD_ORE, Items.RAW_GOLD));
        addDrop(ModBlocks.GRANITE_DIAMOND_ORE, oreDrops(ModBlocks.GRANITE_DIAMOND_ORE, Items.DIAMOND));
        addDrop(ModBlocks.GRANITE_COPPER_ORE, copperOreDrops(ModBlocks.GRANITE_COPPER_ORE));
        addDrop(ModBlocks.GRANITE_LAPIS_ORE, lapisOreDrops(ModBlocks.GRANITE_LAPIS_ORE));
        addDrop(ModBlocks.GRANITE_REDSTONE_ORE, redstoneOreDrops(ModBlocks.GRANITE_REDSTONE_ORE));
        addDrop(ModBlocks.DIORITE_COAL_ORE, oreDrops(ModBlocks.DIORITE_COAL_ORE, Items.COAL));
        addDrop(ModBlocks.DIORITE_EMERALD_ORE, oreDrops(ModBlocks.DIORITE_EMERALD_ORE, Items.EMERALD));
        addDrop(ModBlocks.DIORITE_IRON_ORE, oreDrops(ModBlocks.DIORITE_IRON_ORE, Items.RAW_IRON));
        addDrop(ModBlocks.DIORITE_GOLD_ORE, oreDrops(ModBlocks.DIORITE_GOLD_ORE, Items.RAW_GOLD));
        addDrop(ModBlocks.DIORITE_DIAMOND_ORE, oreDrops(ModBlocks.DIORITE_DIAMOND_ORE, Items.DIAMOND));
        addDrop(ModBlocks.DIORITE_COPPER_ORE, copperOreDrops(ModBlocks.DIORITE_COPPER_ORE));
        addDrop(ModBlocks.DIORITE_LAPIS_ORE, lapisOreDrops(ModBlocks.DIORITE_LAPIS_ORE));
        addDrop(ModBlocks.DIORITE_REDSTONE_ORE, redstoneOreDrops(ModBlocks.DIORITE_REDSTONE_ORE));
        addDrop(ModBlocks.CALCITE_COAL_ORE, oreDrops(ModBlocks.CALCITE_COAL_ORE, Items.COAL));
        addDrop(ModBlocks.CALCITE_EMERALD_ORE, oreDrops(ModBlocks.CALCITE_EMERALD_ORE, Items.EMERALD));
        addDrop(ModBlocks.CALCITE_IRON_ORE, oreDrops(ModBlocks.CALCITE_IRON_ORE, Items.RAW_IRON));
        addDrop(ModBlocks.CALCITE_GOLD_ORE, oreDrops(ModBlocks.CALCITE_GOLD_ORE, Items.RAW_GOLD));
        addDrop(ModBlocks.CALCITE_DIAMOND_ORE, oreDrops(ModBlocks.CALCITE_DIAMOND_ORE, Items.DIAMOND));
        addDrop(ModBlocks.CALCITE_COPPER_ORE, copperOreDrops(ModBlocks.CALCITE_COPPER_ORE));
        addDrop(ModBlocks.CALCITE_LAPIS_ORE, lapisOreDrops(ModBlocks.CALCITE_LAPIS_ORE));
        addDrop(ModBlocks.CALCITE_REDSTONE_ORE, redstoneOreDrops(ModBlocks.CALCITE_REDSTONE_ORE));
        addDrop(ModBlocks.DRIPSTONE_COAL_ORE, oreDrops(ModBlocks.DRIPSTONE_COAL_ORE, Items.COAL));
        addDrop(ModBlocks.DRIPSTONE_EMERALD_ORE, oreDrops(ModBlocks.DRIPSTONE_EMERALD_ORE, Items.EMERALD));
        addDrop(ModBlocks.DRIPSTONE_IRON_ORE, oreDrops(ModBlocks.DRIPSTONE_IRON_ORE, Items.RAW_IRON));
        addDrop(ModBlocks.DRIPSTONE_GOLD_ORE, oreDrops(ModBlocks.DRIPSTONE_GOLD_ORE, Items.RAW_GOLD));
        addDrop(ModBlocks.DRIPSTONE_DIAMOND_ORE, oreDrops(ModBlocks.DRIPSTONE_DIAMOND_ORE, Items.DIAMOND));
        addDrop(ModBlocks.DRIPSTONE_COPPER_ORE, copperOreDrops(ModBlocks.DRIPSTONE_COPPER_ORE));
        addDrop(ModBlocks.DRIPSTONE_LAPIS_ORE, lapisOreDrops(ModBlocks.DRIPSTONE_LAPIS_ORE));
        addDrop(ModBlocks.DRIPSTONE_REDSTONE_ORE, redstoneOreDrops(ModBlocks.DRIPSTONE_REDSTONE_ORE));
        addDrop(ModBlocks.TUFF_COAL_ORE, oreDrops(ModBlocks.TUFF_COAL_ORE, Items.COAL));
        addDrop(ModBlocks.TUFF_EMERALD_ORE, oreDrops(ModBlocks.TUFF_EMERALD_ORE, Items.EMERALD));
        addDrop(ModBlocks.TUFF_IRON_ORE, oreDrops(ModBlocks.TUFF_IRON_ORE, Items.RAW_IRON));
        addDrop(ModBlocks.TUFF_GOLD_ORE, oreDrops(ModBlocks.TUFF_GOLD_ORE, Items.RAW_GOLD));
        addDrop(ModBlocks.TUFF_DIAMOND_ORE, oreDrops(ModBlocks.TUFF_DIAMOND_ORE, Items.DIAMOND));
        addDrop(ModBlocks.TUFF_COPPER_ORE, copperOreDrops(ModBlocks.TUFF_COPPER_ORE));
        addDrop(ModBlocks.TUFF_LAPIS_ORE, lapisOreDrops(ModBlocks.TUFF_LAPIS_ORE));
        addDrop(ModBlocks.TUFF_REDSTONE_ORE, redstoneOreDrops(ModBlocks.TUFF_REDSTONE_ORE));
        addDrop(ModBlocks.MOSSY_COAL_ORE, oreDrops(ModBlocks.MOSSY_COAL_ORE, Items.COAL));
        addDrop(ModBlocks.MOSSY_EMERALD_ORE, oreDrops(ModBlocks.MOSSY_EMERALD_ORE, Items.EMERALD));
        addDrop(ModBlocks.MOSSY_IRON_ORE, oreDrops(ModBlocks.MOSSY_IRON_ORE, Items.RAW_IRON));
        addDrop(ModBlocks.MOSSY_GOLD_ORE, oreDrops(ModBlocks.MOSSY_GOLD_ORE, Items.RAW_GOLD));
        addDrop(ModBlocks.MOSSY_DIAMOND_ORE, oreDrops(ModBlocks.MOSSY_DIAMOND_ORE, Items.DIAMOND));
        addDrop(ModBlocks.MOSSY_COPPER_ORE, copperOreDrops(ModBlocks.MOSSY_COPPER_ORE));
        addDrop(ModBlocks.MOSSY_LAPIS_ORE, lapisOreDrops(ModBlocks.MOSSY_LAPIS_ORE));
        addDrop(ModBlocks.MOSSY_REDSTONE_ORE, redstoneOreDrops(ModBlocks.MOSSY_REDSTONE_ORE));
        addDrop(ModBlocks.BASALT_QUARTZ_ORE,oreDrops(ModBlocks.BASALT_QUARTZ_ORE,Items.QUARTZ));
        addDrop(ModBlocks.BLACKSTONE_QUARTZ_ORE,oreDrops(ModBlocks.BLACKSTONE_QUARTZ_ORE,Items.QUARTZ));
        addDrop(ModBlocks.BASALT_GOLD_ORE,multipleOreDrops(ModBlocks.BASALT_GOLD_ORE,
                Items.GOLD_NUGGET,2f,6f));
    }

        public LootTable.Builder multipleOreDrops(Block drop, Item item, float minDrops, float maxDrops) {
            RegistryWrapper.Impl<Enchantment> impl = this.registries.getOrThrow(RegistryKeys.ENCHANTMENT);
            return this.dropsWithSilkTouch(drop, this.applyExplosionDecay(drop, ((LeafEntry.Builder<?>)
                    ItemEntry.builder(item).apply(SetCountLootFunction.builder(UniformLootNumberProvider.create(minDrops, maxDrops))))
                    .apply(ApplyBonusLootFunction.oreDrops(impl.getOrThrow(Enchantments.FORTUNE)))));
    }
}
